<a href="https://colab.research.google.com/github/ayushNautiyal35/Deep_Learning_basic_to_advanced/blob/main/Basic_of_nlp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#tokenization


In [138]:
import nltk


In [139]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


True

In [140]:
paragraph="Sisters and Brothers of America,It fills my heart with joy unspeakable to rise in response to the warm and cordial welcome which you have given us. I thank you in the name of the most ancient order of monks in the world, I thank you in the name of the mother of religions, and I thank you in the name of millions and millions of Hindu people of all classes and sects.My thanks, also, to some of the speakers on this platform who, referring to the delegates from the Orient, have told you that these men from far-off nations may well claim the honor of bearing to different lands the idea of toleration. I am proud to belong to a religion which has taught the world both tolerance and universal acceptance. We believe not only in universal toleration, but we accept all religions as true. I am proud to belong to a nation which has sheltered the persecuted and the refugees of all religions and all nations of the earth. I am proud to tell you that we have gathered in our bosom the purest remnant of the Israelites, who came to Southern India and took refuge with us in the very year in which their holy temple was shat­tered to pieces by Roman tyranny. I am proud to belong to the religion which has sheltered and is still fostering the remnant of the grand Zoroastrian nation. I will quote to you, brethren, a few lines from a hymn which I remember to have repeated from my earliest boyhood, which is every day repeated by millions of human beings: “As the different streams having their sources in different paths which men take through different tendencies, various though they appear, crooked or straight, all lead to Thee.”The present convention, which is one of the most august assemblies ever held, is in itself a vindication, a declaration to the world of the wonderful doctrine preached in the Gita: “Whosoever comes to Me, through whatsoever form, I reach him; all men are struggling through paths which in the end lead to me.” Sectarianism, bigotry, and its horrible descen­dant, fanaticism, have long possessed this beautiful earth. They have filled the earth with vio­lence, drenched it often and often with human blood, destroyed civilization and sent whole nations to despair. Had it not been for these horrible demons, human society would be far more advanced than it is now. But their time is come; and I fervently hope that the bell that tolled this morning in honor of this convention may be the death-knell of all fanaticism, of all persecutions with the sword or with the pen, and of all uncharitable feelings between persons wending their way to the same goal."

In [141]:
#tokenize
sentences=nltk.sent_tokenize(paragraph)
sentences

['Sisters and Brothers of America,It fills my heart with joy unspeakable to rise in response to the warm and cordial welcome which you have given us.',
 'I thank you in the name of the most ancient order of monks in the world, I thank you in the name of the mother of religions, and I thank you in the name of millions and millions of Hindu people of all classes and sects.My thanks, also, to some of the speakers on this platform who, referring to the delegates from the Orient, have told you that these men from far-off nations may well claim the honor of bearing to different lands the idea of toleration.',
 'I am proud to belong to a religion which has taught the world both tolerance and universal acceptance.',
 'We believe not only in universal toleration, but we accept all religions as true.',
 'I am proud to belong to a nation which has sheltered the persecuted and the refugees of all religions and all nations of the earth.',
 'I am proud to tell you that we have gathered in our bosom 

In [142]:
len(sentences)

11

In [143]:
words=nltk.word_tokenize(paragraph)
words

['Sisters',
 'and',
 'Brothers',
 'of',
 'America',
 ',',
 'It',
 'fills',
 'my',
 'heart',
 'with',
 'joy',
 'unspeakable',
 'to',
 'rise',
 'in',
 'response',
 'to',
 'the',
 'warm',
 'and',
 'cordial',
 'welcome',
 'which',
 'you',
 'have',
 'given',
 'us',
 '.',
 'I',
 'thank',
 'you',
 'in',
 'the',
 'name',
 'of',
 'the',
 'most',
 'ancient',
 'order',
 'of',
 'monks',
 'in',
 'the',
 'world',
 ',',
 'I',
 'thank',
 'you',
 'in',
 'the',
 'name',
 'of',
 'the',
 'mother',
 'of',
 'religions',
 ',',
 'and',
 'I',
 'thank',
 'you',
 'in',
 'the',
 'name',
 'of',
 'millions',
 'and',
 'millions',
 'of',
 'Hindu',
 'people',
 'of',
 'all',
 'classes',
 'and',
 'sects.My',
 'thanks',
 ',',
 'also',
 ',',
 'to',
 'some',
 'of',
 'the',
 'speakers',
 'on',
 'this',
 'platform',
 'who',
 ',',
 'referring',
 'to',
 'the',
 'delegates',
 'from',
 'the',
 'Orient',
 ',',
 'have',
 'told',
 'you',
 'that',
 'these',
 'men',
 'from',
 'far-off',
 'nations',
 'may',
 'well',
 'claim',
 'the',


In [144]:
len(words)

506

#Stemming

In [145]:
from nltk.stem import PorterStemmer
from nltk.corpus import stopwords

In [146]:
stemmer=PorterStemmer()


In [147]:
stem_corpus=[]

In [148]:
#stop words
for i in range(len(sentences)):
  words=nltk.word_tokenize(sentences[i])
  words=[stemmer.stem(word) for word in words if word not in set(stopwords.words('english'))]
  s=' '.join(words)
  stem_corpus.append(s)

In [149]:
stem_corpus

['sister brother america , it fill heart joy unspeak rise respons warm cordial welcom given us .',
 'i thank name ancient order monk world , i thank name mother religion , i thank name million million hindu peopl class sects.mi thank , also , speaker platform , refer deleg orient , told men far-off nation may well claim honor bear differ land idea toler .',
 'i proud belong religion taught world toler univers accept .',
 'we believ univers toler , accept religion true .',
 'i proud belong nation shelter persecut refuge religion nation earth .',
 'i proud tell gather bosom purest remnant israelit , came southern india took refug us year holi templ shat\xadter piec roman tyranni .',
 'i proud belong religion shelter still foster remnant grand zoroastrian nation .',
 'i quot , brethren , line hymn i rememb repeat earliest boyhood , everi day repeat million human be : “ as differ stream sourc differ path men take differ tendenc , variou though appear , crook straight , lead thee. ” the pre

#Lemmatization

In [150]:
from nltk.stem import WordNetLemmatizer

In [151]:
lemma_corpus=[]

In [152]:
lemmatizer=WordNetLemmatizer()

In [153]:
for i in range(len(sentences)):
  words=nltk.word_tokenize(sentences[i])
  words=[lemmatizer.lemmatize(word) for word in words if word not in set(stopwords.words('english'))]
  l=' '.join(words)
  lemma_corpus.append(l)

In [154]:
lemma_corpus

['Sisters Brothers America , It fill heart joy unspeakable rise response warm cordial welcome given u .',
 'I thank name ancient order monk world , I thank name mother religion , I thank name million million Hindu people class sects.My thanks , also , speaker platform , referring delegate Orient , told men far-off nation may well claim honor bearing different land idea toleration .',
 'I proud belong religion taught world tolerance universal acceptance .',
 'We believe universal toleration , accept religion true .',
 'I proud belong nation sheltered persecuted refugee religion nation earth .',
 'I proud tell gathered bosom purest remnant Israelites , came Southern India took refuge u year holy temple shat\xadtered piece Roman tyranny .',
 'I proud belong religion sheltered still fostering remnant grand Zoroastrian nation .',
 'I quote , brother , line hymn I remember repeated earliest boyhood , every day repeated million human being : “ As different stream source different path men tak

#Bag of words

In [155]:
import re

In [156]:
corpus=[]

In [157]:
#for sentences
for i in range(len(sentences)):
  review=re.sub('[^a-zA-Z]',' ',sentences[i])
  review=review.lower()
  review=review.split()
  review=[lemmatizer.lemmatize(word) for word in words if not word in set(stopwords.words('english'))]
  review=' '.join(review)
  corpus.append(review)

In [158]:
#bow
from sklearn.feature_extraction.text import CountVectorizer


In [159]:
cv=CountVectorizer()
x=cv.fit_transform(corpus).toarray()

In [160]:
x

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1]])

#tf-idf

In [161]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [162]:
for i in range(len(sentences)):
  review=re.sub('[^a-zA-Z]',' ',sentences[i])
  review=review.lower()
  review=review.split()
  review=[lemmatizer.lemmatize(word) for word in words if not word in set(stopwords.words('english'))]
  review=' '.join(review)
  corpus.append(review)

In [163]:
tf=TfidfVectorizer()
y=tf.fit_transform(corpus).toarray()

In [164]:
y

array([[0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
        0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
        0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
        0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
        0.20851441, 0.20851441, 0.20851441],
       [0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
        0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
        0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
        0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
        0.20851441, 0.20851441, 0.20851441],
       [0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
        0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
        0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
        0.20851441, 0.20851441, 0.20851441, 0.20851441, 0.20851441,
        0.20851441, 0.20851441, 0.20851441],
       [0.20851441, 0.20851441, 0.20851441, 0.208

#Word2Vec

In [165]:
from gensim.models import Word2Vec

In [172]:

# Preprocessing the data
text = re.sub(r'\[[0-9]*\]',' ',paragraph)
text = re.sub(r'\s+',' ',text)
text = text.lower()
text = re.sub(r'\d',' ',text)
text = re.sub(r'\s+',' ',text)

# Preparing the dataset
sentences = nltk.sent_tokenize(text)

sentences = [nltk.word_tokenize(sentence) for sentence in sentences]

for i in range(len(sentences)):
    sentences[i] = [word for word in sentences[i] if word not in stopwords.words('english')]


# Training the Word2Vec model
model = Word2Vec(sentences, min_count=1)


In [176]:
model

In [173]:
words = model.wv.key_to_index
words

{',': 0,
 '.': 1,
 'proud': 2,
 'different': 3,
 'men': 4,
 'nations': 5,
 'millions': 6,
 'religions': 7,
 'world': 8,
 'human': 9,
 'name': 10,
 'thank': 11,
 'earth': 12,
 'belong': 13,
 ';': 14,
 'paths': 15,
 'lead': 16,
 'may': 17,
 '”': 18,
 'honor': 19,
 'horrible': 20,
 'convention': 21,
 'nation': 22,
 'universal': 23,
 'fanaticism': 24,
 'toleration': 25,
 'sheltered': 26,
 'often': 27,
 'religion': 28,
 'repeated': 29,
 '“': 30,
 ':': 31,
 'us': 32,
 'remnant': 33,
 'tell': 34,
 'shat\xadtered': 35,
 'temple': 36,
 'holy': 37,
 'tolerance': 38,
 'year': 39,
 'refuge': 40,
 'took': 41,
 'india': 42,
 'acceptance': 43,
 'southern': 44,
 'israelites': 45,
 'came': 46,
 'taught': 47,
 'believe': 48,
 'accept': 49,
 'true': 50,
 'purest': 51,
 'bosom': 52,
 'persecuted': 53,
 'refugees': 54,
 'gathered': 55,
 'goal': 56,
 'well': 57,
 'idea': 58,
 'response': 59,
 'order': 60,
 'ancient': 61,
 'given': 62,
 'welcome': 63,
 'cordial': 64,
 'warm': 65,
 'rise': 66,
 'mother': 67,


In [178]:
similar=model.wv['brothers']
similar

array([-6.3818606e-04,  1.4335120e-03, -1.1984971e-03, -4.0562027e-03,
        8.6473691e-04, -9.7025381e-03,  1.4124376e-03, -4.1313875e-03,
       -5.8236900e-03,  3.7828491e-03,  1.4528503e-03,  3.6540753e-03,
        8.8380428e-04, -9.5174871e-03,  9.9999364e-03, -3.5228769e-03,
       -2.1835600e-03,  7.1107186e-03,  7.0992050e-05,  3.0028191e-03,
        2.2576267e-03,  2.4026020e-03,  6.7529278e-03,  9.4605740e-03,
       -5.7179859e-04, -3.4201220e-03,  4.5662895e-03, -8.3451141e-03,
        8.4367599e-03,  2.4070591e-03,  6.0156672e-03,  2.8053550e-03,
       -1.3258697e-03,  9.5134438e-04, -4.8039113e-03,  9.1102384e-03,
        5.0453646e-03,  3.5907873e-03, -5.0048199e-03, -8.6740386e-03,
        7.9266075e-03,  2.9232714e-03, -4.2507667e-03, -8.6779650e-03,
       -3.9234567e-03,  1.4101350e-03, -9.1830706e-03,  4.5886733e-05,
        2.8025671e-03, -9.9307718e-03, -1.4226236e-04, -6.0599726e-03,
       -3.5959971e-03, -1.6222302e-03, -9.9614561e-03, -3.6115020e-03,
      

In [175]:
vector=model.wv.most_similar('sisters')
vector

[('far', 0.2560371458530426),
 ('temple', 0.2120853066444397),
 ('ever', 0.1944715827703476),
 ('lands', 0.182297483086586),
 ('southern', 0.17889808118343353),
 (',', 0.17851458489894867),
 ('given', 0.1782148778438568),
 ('refugees', 0.172827810049057),
 ('civilization', 0.16556864976882935),
 ('pen', 0.15677206218242645)]