<a href="https://colab.research.google.com/github/ayushNautiyal35/Deep_Learning_basic_to_advanced/blob/main/word_embeddings_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

importing one hot encoder for changing the sentences to the resutant matrix

In [1]:
from tensorflow.keras.preprocessing.text import one_hot

defining sentences

In [2]:
sent=[
    'The glass of milk',
    'the glass of water',
    'the cup of tea',
    'i am a good boy',
    'I am a good Coder',
    'I AM GOOD',
    'understanding what I say?'
]

defining vocabulary size for the sentences

In [3]:
vocab_size=10000

nowrepresenting the sentences as one hot encoding

In [4]:
onehot_repr=[one_hot(words,vocab_size) for words in sent]
print(onehot_repr)

[[1035, 4987, 5942, 6856], [1035, 4987, 5942, 6898], [1035, 5726, 5942, 8193], [4212, 7036, 6860, 8247, 5651], [4212, 7036, 6860, 8247, 9878], [4212, 7036, 8247], [4308, 3342, 4212, 3560]]


in above we can observe that same word have same index

now representation as word embedding

In [5]:
from tensorflow.keras.layers import Embedding

In [6]:
from tensorflow.keras.models import Sequential

In [7]:
#for padding purpose
from tensorflow.keras.preprocessing.sequence import pad_sequences

In [9]:
import numpy as np

In [10]:
#defining sentence length by which the length will not exceed
sen_len=8

In [13]:
#we are using pre as it will give zero before all if we use post the 0 at last
embedded_docs=pad_sequences(onehot_repr,padding='pre',maxlen=sen_len)
print(embedded_docs)

[[1035 4987 5942 6856    0    0    0    0]
 [1035 4987 5942 6898    0    0    0    0]
 [1035 5726 5942 8193    0    0    0    0]
 [4212 7036 6860 8247 5651    0    0    0]
 [4212 7036 6860 8247 9878    0    0    0]
 [4212 7036 8247    0    0    0    0    0]
 [4308 3342 4212 3560    0    0    0    0]]


defining dimensions which we want to add

In [14]:
dim=10


defining models

In [15]:
model=Sequential()
model.add(Embedding(vocab_size,dim,input_length=sen_len))

In [16]:
model.compile('adam','mse')

In [17]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [18]:
print(model.predict(embedded_docs))

1/1 [==============================] - 0s 81ms/step
[[[ 0.00034144  0.0113222  -0.03744091  0.01448039  0.02768883
    0.00650821 -0.0054193   0.01080693 -0.02113866 -0.03435139]
  [-0.02480234  0.00700003  0.01161727  0.04146869  0.03708786
    0.048456   -0.03344904 -0.03488945  0.01847606  0.00913267]
  [ 0.04636539 -0.03190567 -0.02236944 -0.0094155  -0.02270411
   -0.01577014  0.01393482  0.02836788 -0.01225623 -0.01886926]
  [ 0.0082037   0.01538267  0.02895014 -0.02711824  0.03744799
    0.02975495  0.01311641  0.02897676 -0.02351039 -0.00521646]
  [-0.01802314 -0.02015879  0.01748968 -0.04425336 -0.02836777
    0.01272781  0.0404661   0.01780673 -0.0492167  -0.04440181]
  [-0.01802314 -0.02015879  0.01748968 -0.04425336 -0.02836777
    0.01272781  0.0404661   0.01780673 -0.0492167  -0.04440181]
  [-0.01802314 -0.02015879  0.01748968 -0.04425336 -0.02836777
    0.01272781  0.0404661   0.01780673 -0.0492167  -0.04440181]
  [-0.01802314 -0.02015879  0.01748968 -0.04425336 -0.02836

In [19]:
embedded_docs[0]

array([1035, 4987, 5942, 6856,    0,    0,    0,    0], dtype=int32)

here each is represented as dimension of 10

In [20]:
print(model.predict(embedded_docs)[0])

1/1 [==============================] - 0s 14ms/step
[[ 0.00034144  0.0113222  -0.03744091  0.01448039  0.02768883  0.00650821
  -0.0054193   0.01080693 -0.02113866 -0.03435139]
 [-0.02480234  0.00700003  0.01161727  0.04146869  0.03708786  0.048456
  -0.03344904 -0.03488945  0.01847606  0.00913267]
 [ 0.04636539 -0.03190567 -0.02236944 -0.0094155  -0.02270411 -0.01577014
   0.01393482  0.02836788 -0.01225623 -0.01886926]
 [ 0.0082037   0.01538267  0.02895014 -0.02711824  0.03744799  0.02975495
   0.01311641  0.02897676 -0.02351039 -0.00521646]
 [-0.01802314 -0.02015879  0.01748968 -0.04425336 -0.02836777  0.01272781
   0.0404661   0.01780673 -0.0492167  -0.04440181]
 [-0.01802314 -0.02015879  0.01748968 -0.04425336 -0.02836777  0.01272781
   0.0404661   0.01780673 -0.0492167  -0.04440181]
 [-0.01802314 -0.02015879  0.01748968 -0.04425336 -0.02836777  0.01272781
   0.0404661   0.01780673 -0.0492167  -0.04440181]
 [-0.01802314 -0.02015879  0.01748968 -0.04425336 -0.02836777  0.01272781
 